### ISSUE TITLE
It maybe a silly question but...

### ISSUE THREAD

**Issue by tonydspaniard** [ruimarinho/docker-bitcoin-core#54]
First of all, thank you very much for your work. I am running into an issue that it maybe silly as I am new to docker but I cannot connect to the RPC from my application. 

When I do from console, all is smooth:

```
 $ docker exec bitcoincore_1 bitcoin-cli -regtest -rpcuser=rpcuser -rpcpassword=rpcpassword getmininginfo
{
  "blocks": 0,
  "currentblockweight": 0,
  "currentblocktx": 0,
  "difficulty": 4.656542373906925e-10,
  "errors": "",
  "networkhashps": 0,
  "pooledtx": 0,
  "chain": "regtest"
}
```
But when I try to connect from my app using an RPC client, it fails: 

```
Message: cURL error 7: Failed to connect to bitcoincore port 8332: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```
This is how I configured the services:

```yaml
services:
  bitcoincore:
    image: ruimarinho/bitcoin-core:latest
    restart: always
    command:
      -printtoconsole
      -regtest=1
      -rpcuser=rpcuser
      -rpcpassword=rpcpassword
    ports:
      - "8332:8332"
  php:
    build: .
    ports:
      - "80:80"
    depends_on:
      - bitcoincore
      - mysqldb
    links:
      - bitcoincore:bitcoincore
      - mysqldb:mysqldb
    volumes:
       .... 
```
Any help would be highly appreciated. And apologies if its a lame question. Thanks in advance.
